; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
board = rpipicow
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
src_filter =
    +<*>
    -<provisioning_page/node_modules>
build_flags =
	-DLWJSON_IGNORE_USER_OPTS
	-DPIO_FRAMEWORK_ARDUINO_ENABLE_FREERTOS
lib_deps =
	https://github.com/MaJerle/lwjson.git#2a8c724d039cd6d6bd9f7b91d3d710bce9acdb6a
	vshymanskyy/Preferences@2.2.2
	mishamyrt/CPreferences@1.2.0
	mishamyrt/LightComposer@2.0.2
	mishamyrt/CWiFiManager@1.0.4
	mishamyrt/CPubSub@1.1.1
	mishamyrt/CWebServer@1.1.0
	mishamyrt/CUpdate@1.1.0
	mishamyrt/HomeAssistantJSON@2.0.0
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m

[env:release]
board = rpipicow
