#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#define CONFIG_MQTT_BUFFER_SIZE 1024
#define CONFIG_MQTT_RECONNECT_DELAY_MS 5000

#define CONFIG_LIGHT_LED_COUNT 92
#define CONFIG_LIGHT_COLOR_KELVIN_INITIAL 2857
#define CONFIG_LIGHT_COLOR_KELVIN_WARM 2000
#define CONFIG_LIGHT_COLOR_KELVIN_COLD 7407
#define CONFIG_LIGHT_TRANSITION_COLOR 400
#define CONFIG_LIGHT_COLOR_ORDER LC_ORDER_GRB
#define CONFIG_LIGHT_BRIGHTNESS_MIN 10
#define CONFIG_LIGHT_BRIGHTNESS_MAX 255
#define CONFIG_LIGHT_CTL_GPIO 3

#define CONFIG_BEKANT_HEIGHT_MAX 1260
#define CONFIG_BEKANT_HEIGHT_MIN 650
#define CONFIG_BEKANT_HEIGHT_SLOPE 0.09792
#define CONFIG_BEKANT_HEIGHT_BIAS 633.3536
#define CONFIG_BEKANT_PIN_BUTTON_UP 9
#define CONFIG_BEKANT_PIN_BUTTON_DOWN 8
#define CONFIG_BEKANT_PIN_LIN_TX 4
#define CONFIG_BEKANT_PIN_LIN_RX 5
#define CONFIG_BEKANT_LIN_UART

const char *device_id();
const char *device_hostname();
const char *device_name();

#ifdef __cplusplus
}
#endif
