#pragma once

// Common parameters
#define CONFIG_DEVICE_NAME "MyrtDesk"
// Wi-Fi parameters
#define CONFIG_WIFI_SSID "Your SSID" // replace: "Your SSID"
#define CONFIG_WIFI_PASSWORD "Your password" // replace: "Your password"
#define CONFIG_WIFI_RECONNECT_TIMEOUT 30000
#define CONFIG_WIFI_START_DELAY 800
// MQTT parameters
#define CONFIG_MQTT_HOST \
	"your.mqtt.server.local" // replace: "your.mqtt.server.local"
#define CONFIG_MQTT_PORT 1883
#define CONFIG_MQTT_BUFFER_SIZE 1024
// GPIO pins
#define CONFIG_PIN_LED_CTL 3
#define CONFIG_PIN_LIN_TX 4
#define CONFIG_PIN_LIN_RX 5
#define CONFIG_PIN_BUTTON_UP 9
#define CONFIG_PIN_BUTTON_DOWN 8
// Bekant legs parameters
#define CONFIG_BEKANT_HEIGHT_MAX 1260
#define CONFIG_BEKANT_HEIGHT_MIN 650
#define CONFIG_BEKANT_HEIGHT_SLOPE 0.09792
#define CONFIG_BEKANT_HEIGHT_BIAS 633.3536
#define CONFIG_BEKANT_LIN_UART Serial2
// Light parameters
#define CONFIG_LIGHT_WORKER_PIO pio1
#define CONFIG_LIGHT_WORKER_SM 1
#define CONFIG_LIGHT_LED_COUNT 92
#define CONFIG_LIGHT_COLOR_CORRECTION 0xFF8173
#define CONFIG_LIGHT_COLOR_INITIAL 0xFFBD77
#define CONFIG_LIGHT_COLOR_CONNECTED 0x38FFB6
#define CONFIG_LIGHT_MIREDS_MIN 142
#define CONFIG_LIGHT_MIREDS_MAX 454
#define CONFIG_LIGHT_COLOR_TRANSITION_MS 700
